### ISSUE TITLE
Sakura no Mori Dreamers

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/RLDManager#1]
its not me, but could you help [this guy](https://forums.fuwanovel.net/topic/17420-hack-for-sakuranomori-dreamers/)?
he gave me the script but idk since your tools not compatible, btw here is the [script](https://drive.google.com/file/d/0B4E8zrOX6ZdWRGRycDJWQXViSjQ/view?usp=sharing)

**Comment by marcussacana** [comment]
https://github.com/marcussacana/RLDManager/blob/master/RLDManager/Main.cs#L191

**Comment by 0xh3LL0** [comment]
nice!

**Comment by 0xh3LL0** [comment]
just question though,
how long did you take to get the brute-force key?
it says o your program 1-2 hours, but how long it exactly?
i have core i3

**Comment by marcussacana** [comment]
He create 2 threads...
The frist thread search by valid a key from 4.294.967.295 to 0
the second thread search a valid key from 0 to 4.294.967.295
it's imposible to know when he found because the key can be a small value by sample 350.121
the program will found fast if is the case, or will take a long time if in the half of the value by sample the 2.147.483.647...
Sorry, i don't know... but i have i5, this is the time i needs wait to found the sakura key

**Comment by 0xh3LL0** [comment]
aw man, 4 billion...
guess, i cant handle that,

thank you, and good luck!
guess i'll ask you again next time =)
