### ISSUE TITLE
I have some problems. P.S.: Machine translation. Best able to communicate in Chinese.

### ISSUE THREAD

**Issue by a65090482** [marcussacana/RLDManager#2]
I found in the "Imouto Paradise! 3" for a script key when opening the script again failed. The same is true for other scripts. I don't know if other games developed with the same engine will do the same.

**Comment by marcussacana** [comment]
Send samples of the script

**Comment by a65090482** [comment]
[
[etc.zip](https://github.com/marcussacana/RLDManager/files/2819813/etc.zip)

](url)

**Comment by a65090482** [comment]
> Send samples of the script

I have already sent it.

**Comment by a65090482** [comment]
Re-expression and Translation: I used RLD Manager to extract the key of the script "Imouto Paradise! 3" and then used the key corresponding to that script to decrypt it, which met with a failure of decryption.

**Comment by marcussacana** [comment]
Thx for the feedback, your issue is now fixed, if you see any other problem just create a new issue,
I recommend to you too, test the "Unsafe" branch, this unsafe branch have a more accurate string search but can have some problems with certain games.
![image](https://user-images.githubusercontent.com/10576957/52123507-7c19b280-260d-11e9-9ad3-d5ede7585178.png)
