### ISSUE TITLE
Feedback BUG, optimization and development tools.

### ISSUE THREAD

**Issue by a65090482** [marcussacana/RLDManager#3]
Arc_conv find key faster than RLDManager, and some games developed by the same engine only produce a portion of the text (RLDManager). Arc_conv is as fast and accurate as RLDManager. Perhaps it would be better to refer to Arc_conv to improve the RLDManager. ←(not sure).
https://mega.nz/#!x9EGRYLb!a2i-f83XZnZfd_C9EdvJERwe7R1JdtAPZ7nKTaXxCTc

**Comment by a65090482** [comment]
Example: "Imouto Paradise! 3" RLD would have displayed more text, but it actually displayed less text than when playing the game.

**Comment by marcussacana** [comment]
Well... no idea, I will need probabbly need rewrite the tool from begin...
To this, well... one day, maybe? My tools is everything for personal usage, I don't care to add a proper ui as you can see... If is a small bug I can solve when someone request, but rewrite from zero only if I want translate a game to me, yes... I translate games for myself, it's like a hobby

About the find key feature, probabbly I can do something better if use the arc_conv algorithm as base, but not with the same speed, it's impossible do like the arc_conv since he is a tool writed in assembly, the .NET don't will have the same speed if I write something based in the arc_conv algorithm.
And after find the key we can use in the arc_conv or RLDManager, so, basically you can find the key with the arc_conv and put in the RLDManager.

**Comment by a65090482** [comment]
Decrypting "Bunny Paradise" with the resulting key has failed. The key of 0xF8CF34F2 generated by arc_conv can be decrypted successfully. The key generated by arc_conv is 0x20141131. Editorial Tools (Translated):
[Ineditor_2_1_2.zip](https://github.com/marcussacana/RLDManager/files/2854954/Ineditor_2_1_2.zip)

[BunnyParadise rld, and exe.zip](https://github.com/marcussacana/RLDManager/files/2854994/BunnyParadise.rld.and.exe.zip)

**Comment by a65090482** [comment]
> 
> 
> Well... no idea, I will need probabbly need rewrite the tool from begin...
> To this, well... one day, maybe? My tools is everything for personal usage, I don't care to add a proper ui as you can see... If is a small bug I can solve when someone request, but rewrite from zero only if I want translate a game to me, yes... I translate games for myself, it's like a hobby
> 
> About the find key feature, probabbly I can do something better if use the arc_conv algorithm as base, but not with the same speed, it's impossible do like the arc_conv since he is a tool writed in assembly, the .NET don't will have the same speed if I write something based in the arc_conv algorithm.
> And after find the key we can use in the arc_conv or RLDManager, so, basically you can find the key with the arc_conv and put in the RLDManager.

I replied.
